first modifications for in and check

diff --git a/bin/check b/bin/check
--- a/bin/check
+++ b/bin/check
@@ -1,5 +1,51 @@
-#!/bin/sh
+# #!/bin/sh
+# set -eu -o pipefail
+# exec 3>&1 1>&2
+#
+# jq '[.version // empty]' <&0 >&3
+
+#!/bin/bash
+
 set -eu -o pipefail
 exec 3>&1 1>&2
 
-jq '[.version // empty]' <&0 >&3
+payload=$(mktemp /tmp/resource-check.XXXXXX)
+cat > "${payload}" <&0
+
+DEBUG=$(jq -r '.source.debug // false' < "${payload}")
+if [ $DEBUG == "true" ]; then
+  set -x
+fi
+
+region=$(jq -r '.source.region // ""' < "${payload}")
+if [ -z "$region" ]; then
+  region=$GCP_REGION
+fi
+
+if [ -z "$region" ]; then
+  echo "Resource configuration error. Unable to determine GCP region"
+  exit 1
+fi
+
+family=$(jq -r '.params.family // ""' < "${payload}")
+if [ -z "${family}" ]; then
+  family=$GCP_IMAGE_FAMILY
+fi
+
+if [ -z "$family" ]; then
+  echo "Resource get configuration error. Unable to determine image family"
+  exit 1
+fi
+
+
+credentials=$(jq -r '.source.credentials // ""' < "${payload}")
+if [ -z "${credentials}" ]; then
+  echo "Resource configuration error. Unable to connect to gcloud api.  Please include credentials."
+  exit 1
+else
+  saveGCloudJsonKey "${credentials}"
+  activateGCloudAccount
+fi
+
+gcloud compute images list --filter="family:${family}" --format="json" --sort-by="creation_date" | jq 'map({ "image": .})' >&3
+#aws ec2 describe-images --region $region $owners $executable_users $filters_param "${filters[@]}" --query "sort_by(Images, &CreationDate)[].ImageId" | jq 'map({ "ami": .})' >&3
diff --git a/bin/in b/bin/in
--- a/bin/in
+++ b/bin/in
@@ -1,12 +1,58 @@
+#
+# #!/bin/sh
+# set -eu -o pipefail
+# exec 3>&1 1>&2
+#
+# jq . < /dev/stdin > /tmp/input
+#
+# DEST="$1"
+#
+# jq '.version.image // empty' /tmp/input > "$DEST/id"
+#
+# jq '{version, metadata: (.metadata // [])}' /tmp/input >&3
 
-#!/bin/sh
+#!/bin/bash
+
 set -eu -o pipefail
 exec 3>&1 1>&2
 
-jq . < /dev/stdin > /tmp/input
-
 DEST="$1"
 
-jq '.version.image // empty' /tmp/input > "$DEST/id"
+payload=$(mktemp /tmp/resource-in.XXXXXX)
+cat > "${payload}" <&0
 
-jq '{version, metadata: (.metadata // [])}' /tmp/input >&3
+DEBUG=$(jq -r '.source.debug // false' < "${payload}")
+if [ $DEBUG == "true" ]; then
+  set -x
+fi
+
+version=$(jq -r '.version.image' < "${payload}")
+
+region=$(jq -r '.source.region // ""' < "${payload}")
+if [ -z "$region" ]; then
+  region=$GCP_REGION
+fi
+
+if [ -z "$region" ]; then
+    echo "Resource configuration error. Unable to determine GCP region"
+  exit 1
+fi
+
+credentials=$(jq -r '.source.credentials // ""' < "${payload}")
+if [ -z "${credentials}" ]; then
+  echo "Resource configuration error. Unable to connect to gcloud api.  Please include credentials."
+  exit 1
+else
+  saveGCloudJsonKey "${credentials}"
+  activateGCloudAccount
+fi
+
+#gcloud compute images list --filter="name:${version}" --format="json" --project your-project > "$DEST/image.json" ##project not needed but keeping as a follow up
+
+gcloud compute images list --filter="name:${version}" --format="json" > "$DEST/image.json"
+
+echo ${version} > $DEST/version.txt
+jq -n --arg version "$version" '{"image":$version}' > $DEST/version.json
+
+
+jq '{"version": {"image": .name}, "metadata": [{"name": "id", "value": .id},{"name": "family", "value": .family},{"name": "creation_ts", "value": .creationTimestamp},{"name": "self_link", "value": .selfLink}]}' < "$DEST/image.json" >&3
